name: HAOS-ZG
on:
  workflow_dispatch:
    inputs:
      targets:
        description: 'Targets to build (comma separated)'
        required: false
        default: 'rpi3_64,rpi4_64,rpi5_64,ova,generic_x86_64,generic_aarch64,green,yellow,panther_x2,ihost,orangepi_cm4'

  schedule:
    - cron: '0 18 26 * *'
#  watch:
#    types: [started]

env:
  RUN_VALIDATION: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TARGETS="${{ github.event.inputs.targets }}"
          else
            TARGETS="rpi3_64,rpi4_64,rpi5_64,ova,generic_x86_64,generic_aarch64,green,yellow,panther_x2,ihost,orangepi_cm4"
          fi
          JSON=$(echo "$TARGETS" | jq -R -c 'split(",")')
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Echo target
        run: echo "Building for ${{ matrix.target }}"
        #target: [generic_aarch64,generic_x86_64]

    #steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Get HAOS-ZG version
        id: get_haos_version
        run: |
          ver=$(curl -s https://api.github.com/repos/home-assistant/operating-system/releases/latest | jq -r '.tag_name')
          echo "HASSOS_VERSION=${ver}" >> $GITHUB_ENV
        
      - name: Initialization environment and Free up disk space
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/archives/*
          sudo rm -rf /var/cache/debconf/*-old
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt clean
          sudo rm -rf /etc/apt/sources.list.d/*
          sudo apt-get -qq update -y
          sudo apt-get -qq autoremove --purge -y
          sudo apt-get -qq clean -y
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          #sudo rm -rf /usr/share/
          df -h


      - name: Clone source code and Change Settings.
        run: |
          git clone https://github.com/home-assistant/operating-system.git -b main
          cp -r buildroot-external operating-system
          cd operating-system
          git submodule update --init
          echo "replace key information"
          sed -i 's|version.home-assistant.io|gitee.com/wuwzn/version/raw/master|g' buildroot-external/package/hassio/hassio.mk
          sed -i 's|ghcr.io/home-assistant|ghcr.nju.edu.cn/wuwweizn|g' buildroot-external/package/hassio/dind-import-containers.sh
          sed -i 's|ghcr.io/home-assistant|ghcr.nju.edu.cn/wuwweizn|g' buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
          sed -i 's|checkonline.home-assistant.io|https://gitee.com/wuwzn/version/raw/master/online.txt|g' buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
          sed -i 's|time.cloudflare.com|cn.ntp.org.cn|g' buildroot-external/rootfs-overlay/etc/systemd/timesyncd.conf
          sed -i 's|green}_defconfig)|green,panther_x2,ihost,orangepi_cm4}_defconfig)|' scripts/update-kernel-upstream.sh
          sed -i '/^set -e$/a export FORCE_UNSAFE_CONFIGURE=1' scripts/enter.sh
          if [ "${{matrix.target}}" == "panther_x2" ]; then
            echo 'source "$BR2_EXTERNAL_HASSOS_PATH/package/firmware_ap6236/Config.in"' >> buildroot-external/Config.in
          fi
          if [ "${{matrix.target}}" == "orangepi_cm4" ]; then
            echo 'source "$BR2_EXTERNAL_HASSOS_PATH/package/firmware_ap6256/Config.in"' >> buildroot-external/Config.in
          fi
          if [ "${{matrix.target}}" == "ihost" ]; then
            echo 'source "$BR2_EXTERNAL_HASSOS_PATH/package/matter/Config.in"' >> buildroot-external/Config.in
            cp -r buildroot-external/board/sonoff/rootfs-overlay/* buildroot-external/rootfs-overlay/
            cp -r buildroot-external/board/sonoff/0001-CMD-read-string-from-fileinto-env.patch buildroot-external/patches/uboot/0001-CMD-read-string-from-fileinto-env.patch
          fi
          
          
          sed -i 's|Etc/UTC|Asia/Shanghai|g' buildroot/system/Config.in

          echo "BR2_PACKAGE_UNZIP=y" >> buildroot-external/configs/${{matrix.target}}_defconfig 
          echo "BR2_TARGET_LOCALTIME=\"Asia/Shanghai\"" >> buildroot-external/configs/${{matrix.target}}_defconfig
          echo -e "${{ secrets.RAUC_CERTIFICATE }}" > cert.pem
          echo -e "${{ secrets.RAUC_PRIVATE_KEY }}" > key.pem

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build 
        shell: 'script -q -e -c "bash {0}"'
        id: build
        run: |
          sleep $((RANDOM % 600))    
          cd operating-system
          max_retries=3
          count=0
          until scripts/enter.sh make -j$(($(nproc) + 1)) ${{matrix.target}}; do
            count=$((count + 1))
            if [ $count -ge $max_retries ]; then
              echo "Build failed after $count attempts."
              exit 1
            fi
            echo "Build failed. Retrying in 30s... (Attempt $count/$max_retries)"
            sleep 30
          done
          
      - name: Get current date
        id: current_date
        run: |
          current_date=$(date +'%Y-%m-%d')
          echo "CURRENT_DATE=${current_date}" >> $GITHUB_ENV
      
      - name: Use current date
        run: echo "Current date is $CURRENT_DATE"

      - name: Upload images to release
        id: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.UPLOAD_TOKEN }}
          file: operating-system/output/images/haos_*
          tag: ${{ env.HASSOS_VERSION }}
          overwrite: true
          file_glob: true
          body: "Home Assistant 国内版镜像，是专为中国大陆用户优化的 Home Assistant 系统镜像。通过替换了版本检测源、Supervisor 镜像源、联网检测源、NTP 服务，预设为中国时区，优化了国内使用环境。解决了官方镜像在国内下载速度慢、部分依赖无法安装的问题。用户可直接使用该镜像安装或升级 Home Assistant，实现开箱即用、快速稳定。"
